services:
  personal-finance:
    image: personal-finance:latest
    container_name: personal-finance
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/personal_finance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Redis@123
      SPRING_DATA_REDIS_TIMEOUT: 60000
      JWT_SECRET: PersonalFinanceSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong2024
      JWT_ACCESS_EXPIRATION: 14400000
      JWT_REFRESH_EXPIRATION: 604800000
      JWT_ROLE_DEFAULT: USER
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      MANAGEMENT_METRICS_TAGS_APPLICATION: spring-boot
      SPRING_PROMETHEUS_METRICS_EXPORT_ENABLED: 'true'
      SENTRY_DSN: ${SENTRY_DSN:-}
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - finance-network
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_started

networks:
  finance-network:
    name: finance-network
    external: true
