services:
  mysql-db:
    image: mysql:8.0.33
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: personal_finance
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: on-failure
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  personal-finance:
    image: personal-finance:latest
    container_name: personal-finance
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/personal_finance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: PersonalFinanceSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong2024
      JWT_ACCESS_EXPIRATION: 14400000
      JWT_REFRESH_EXPIRATION: 604800000
      JWT_ROLE_DEFAULT: USER
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - finance-network
    depends_on:
      mysql-db:
        condition: service_healthy

networks:
  finance-network:
    driver: bridge

volumes:
  mysql-data:
